services:
  postgres:
    # image: ghcr.io/taktekhq/petri:0.1-alpha
    build: ../..
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: oven/bun:1
    working_dir: /app
    volumes: [".:/app"]
    depends_on: [postgres]
